//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunTakipSistemiMvc5.Models.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcStokEntities1 : DbContext
    {
        public DbMvcStokEntities1()
            : base("name=DbMvcStokEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_kategoriler> tbl_kategoriler { get; set; }
        public virtual DbSet<tbl_musteriler> tbl_musteriler { get; set; }
        public virtual DbSet<tbl_personeller> tbl_personeller { get; set; }
        public virtual DbSet<tbl_satislar> tbl_satislar { get; set; }
        public virtual DbSet<tbl_urunler> tbl_urunler { get; set; }
        public virtual DbSet<tbl_adminler> tbl_adminler { get; set; }
    }
}
