//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunTakipSistemiMvc5.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_musteriler()
        {
            this.tbl_satislar = new HashSet<tbl_satislar>();
        }
    
        public int mus_id { get; set; }
        public string mus_ad { get; set; }
        public string mus_soyad { get; set; }
        public string mus_sehir { get; set; }
        public Nullable<decimal> mus_bakiye { get; set; }
        public Nullable<bool> mus_durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_satislar> tbl_satislar { get; set; }
    }
}
